#!/usr/bin/python2

from mininet.net import Mininet
from mininet.topolib import TreeTopo
import os
import time
import json

currPath = os.getcwd()

# Get immediate subdirectories of "tests" directory - ie. all test cases
for testCaseDir in next(os.walk('./tests'))[1]:
    testCaseDir = './tests/' + testCaseDir

    configFile = testCaseDir + '/config.json'
    config = json.load(open(configFile))
    NUM_NODES = config['NUM_NODES']
    MAX_RUNTIME = config['MAX_RUNTIME']

    tree = TreeTopo(depth = 1, fanout = NUM_NODES)
    net = Mininet(topo = tree, xterms = False)
    net.start()

    for host in net.hosts:
        ip = host.IP()
        testScript = testCaseDir + '/node' + ip[-1] + '.json'
        comm = ('python3 ./test.py %s %s &> %s' % (ip, testScript, testCaseDir)) + '/log' + ip[-1]+'.txt &'
        host.cmd(comm)

    print ("\nRunning test: %s..." % testCaseDir)
    time.sleep(MAX_RUNTIME)
    net.stop()
