#!/usr/bin/python3

from mininet.net import Mininet
from mininet.topolib import TreeTopo

tree = TreeTopo(depth = 1, fanout = 3)
net = Mininet(topo = tree)
net.start()

for host in net.hosts:
    ip = host.IP()
    host.cmd(('python3 ./tests/test.py %s &>> log' % ip)+ip[-1]+'.txt &')

net.stop()
