#!/usr/bin/python2

from mininet.net import Mininet
from mininet.topolib import TreeTopo
import os, time

NUM_NODES = 4
MAX_RUNTIME = 25

currPath = os.getcwd()

tree = TreeTopo(depth = 1, fanout = NUM_NODES)
net = Mininet(topo = tree, xterms = False)
net.start()

for host in net.hosts:
    ip = host.IP()
    print(ip)
    comm = ('python3 ./test.py %s &> ./log' % ip)+ip[-1]+'.txt &'
    host.cmd(comm)

print "\nRunning test..."
time.sleep(MAX_RUNTIME)
net.stop()
